7 create final call to action cta section from figma design
world-wide-techies/annon_chat pull request #18
Opened 2023-08-04 14:43 UTC by Oyinbrakemigrace

2023-08-04 14:43 UTC, Oyinbrakemigrace commented
![finalCTA](https://github.com/world-wide-techies/annon_chat/assets/117949160/dd0e0680-8b36-41b1-8b10-b0676dc5572a)

2023-08-04 18:02 UTC, Remi-dee approved these changes
LG

2023-08-07 13:28 UTC, annonymousauthority requested changes
Changes required

2023-08-07 13:28 UTC, annonymousauthority commented on app/components/FinalCTA_comp.js
> +const FinalCTA_comp = () => {
Snake case isn't used for component naming

2023-08-07 13:28 UTC, annonymousauthority commented on app/components/FinalCTA_comp.js
> +          <Image src={finalCtaImg} sizes={20} />
No `alt` attribute here

2023-08-07 13:28 UTC, annonymousauthority commented on app/components/FinalCTA_comp.js
> +const FinalCTA_comp = () => {
Let's use a proper function for naming components not arrow function

2023-08-07 15:40 UTC, Remi-dee approved these changes

2023-08-07 16:44 UTC, annonymousauthority approved these changes
Seen

2023-08-07 16:44 UTC, merged