Remi/components/testimonials branch
world-wide-techies/annon_chat pull request #24
Opened 2023-08-07 12:58 UTC by Remi-dee

## This PR closes
- #6 
- #2

### Description 
- Created testimonial component from figma
- Created Navbar component from figma

### View

![shadow](https://github.com/world-wide-techies/annon_chat/assets/96704300/fb05f02e-0594-4854-a57a-13ee9764f8e2)

2023-08-07 13:04 UTC, Oyinbrakemigrace approved these changes

2023-08-07 13:32 UTC, Remi-dee commented
> ## This PR closes
> * [Create Testimonial Section from Figma Design #6](https://github.com/world-wide-techies/annon_chat/issues/6)
> * [Create Navbar component from Figma design #2](https://github.com/world-wide-techies/annon_chat/issues/2)
> 
> ### Description
> * Created testimonial component from figma
> * Created Navbar component from figma
> 
> ### View
> ![shadow](https://user-images.githubusercontent.com/96704300/258792782-fb05f02e-0594-4854-a57a-13ee9764f8e2.PNG)

Don't review yet

2023-08-07 16:45 UTC, annonymousauthority approved these changes
Seen

2023-08-07 16:45 UTC, annonymousauthority requested changes

2023-08-07 16:45 UTC, annonymousauthority commented on app/components/Nav_comp.js
> +function Nav() {
I'd be more comfortable with a proper elaborate name. Nav is not explanatory enough

2023-08-07 18:47 UTC, Remi-dee commented on app/components/Nav_comp.js
> +function Nav() {
Done with that

2023-08-08 12:43 UTC, annonymousauthority approved these changes
Seen

2023-08-08 12:43 UTC, merged