Add Join Chat Hero Component
world-wide-techies/annon_chat pull request #29
Opened 2023-08-08 01:05 UTC by spadechaser

## Description
This PR introduces the "Join Chat" hero component designed for users to join chat.

## Preview
![preview](https://github.com/world-wide-techies/annon_chat/assets/106241330/ed86c391-0de8-41e1-b44e-c21f396330f8)

2023-08-08 10:17 UTC, Remi-dee requested changes
LG but we do not need to have this component again, as the component UI isn't different from the one on the landing page, just the CTA's should change.

Can we have just the CTA for join a chat?

2023-08-08 12:50 UTC, spadechaser commented
> LG but we do not need to have this component again, as the component UI isn't different from the one on the landing page, just the CTA's should change.
> 
> Can we have just the CTA for join a chat?

did check it out

2023-08-08 16:57 UTC, Remi-dee approved these changes
LG

2023-08-09 13:02 UTC, Oyinbrakemigrace approved these changes

2023-08-09 13:03 UTC, merged