Feature: Dynamic Chatroom Routing with Next.js Routing
world-wide-techies/annon_chat pull request #54
Opened 2023-08-22 16:44 UTC by spadechaser

2023-08-22 17:03 UTC, Remi-dee requested changes
Change

2023-08-22 17:03 UTC, Remi-dee commented on app/[chatroomName]/page.js
> +import { useRouter } from "next/router";
change  "next/router" to "next/navigation"

2023-08-23 20:48 UTC, Remi-dee approved these changes
LG

2023-08-25 07:34 UTC, Oyinbrakemigrace approved these changes

2023-08-25 07:34 UTC, merged