new feature/invite component && minor bug fixes
world-wide-techies/annon_chat pull request #59
Opened 2023-08-31 11:18 UTC by spadechaser

## Description
- This pr introduces the invite view where users can copy the invite link and start a chat.
- Includes minor bug fixes.

## Preview
![preview](https://github.com/world-wide-techies/annon_chat/assets/106241330/295cb9f7-788d-4f53-8ba3-d34533142ca5)

2023-09-02 11:15 UTC, Remi-dee requested changes

2023-09-02 11:15 UTC, Remi-dee commented on app/layout.js
> +    <html lang="en" className="h-full w-full antialiased scroll-smooth">
Why add this class?

2023-09-02 11:15 UTC, Remi-dee commented on app/lib/identityContext.js
> -  const [avatarSelected, setAvatarSelected] = useState(false);
Why remove this line?

2023-09-02 11:15 UTC, Remi-dee commented on app/lib/identityContext.js
> -        avatarSelected,
And this?

2023-09-02 11:17 UTC, spadechaser commented on app/lib/identityContext.js
> -  const [avatarSelected, setAvatarSelected] = useState(false);
lol you added selected avatar and set selected avatar that made the button disabled had to use yours and delete it cause it's void

2023-09-02 11:19 UTC, spadechaser commented on app/layout.js
> +    <html lang="en" className="h-full w-full antialiased scroll-smooth">
I don't see anything wrong with that.

2023-09-02 11:20 UTC, spadechaser commented on app/lib/identityContext.js
> -        avatarSelected,
Because you added one already to the identity context

2023-09-02 11:23 UTC, spadechaser commented on app/lib/identityContext.js
> -        avatarSelected,
The reason why the button was disabled is because you added yours to the context. I had to change it to the one you added to the context and deleted the one I added

2023-09-02 11:24 UTC, Remi-dee commented on app/layout.js
> +    <html lang="en" className="h-full w-full antialiased scroll-smooth">
Alright, if there is no purpose it serves or particular reason of adding it, kindly remove it.

2023-09-02 11:24 UTC, spadechaser commented on app/layout.js
> +    <html lang="en" className="h-full w-full antialiased scroll-smooth">
It's just a normal setting for all the components

2023-09-02 12:00 UTC, Remi-dee approved these changes
LG

2023-09-02 23:05 UTC, Remi-dee approved these changes

2023-09-04 07:58 UTC, annonymousauthority approved these changes
Seen

2023-09-04 07:58 UTC, merged