Feature/fix responsiveness
world-wide-techies/annon_chat pull request #63
Opened 2023-09-09 00:40 UTC by spadechaser

## Description 

- Fixed landing page responsiveness and font.

2023-09-09 10:07 UTC, Remi-dee requested changes

2023-09-09 10:07 UTC, Remi-dee commented on app/page.js
> +      <div className="w-full">
Please revert this change, we are not supporting any width larger than 1500 width

2023-09-09 10:09 UTC, spadechaser commented on app/page.js
> +      <div className="w-full">
On my of the bg image is not meeting both end

2023-09-09 10:10 UTC, spadechaser commented on app/page.js
> +      <div className="w-full">
It's a Mac pc we could make it max-w-3xl or so what do you think ?

2023-09-10 20:27 UTC, Remi-dee approved these changes

2023-09-11 12:53 UTC, Remi-dee approved these changes
LG

2023-09-12 22:29 UTC, merged